services:
  keycloak-mysql:
    container_name: keycloak-mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - keycloak-mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: root
      MYSQL_PASSWORD: akila
      MYSQL_ROOT_PASSWORD: akila

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - keycloak-mysql
    ports:
      - "8181:8080"
    environment:
      KC_DB: mysql
      KC_DB_URL_HOST: keycloak-mysql
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: ["start-dev"]

volumes:
  keycloak-mysql-data:
